pub mod csharp;
pub mod css;
pub mod dart;
pub mod go;
pub mod html;
pub mod java;
pub mod js_ts;
pub mod kotlin;
pub mod lua;
pub mod php;
pub mod python;
pub mod r;
pub mod ruby;
pub mod rust;
pub mod scala;
pub mod shell;
pub mod sql;
pub mod swift;
pub mod zig;

pub use csharp::{CSharpConsoleRule, CSharpStyleRule};
pub use css::CssImportantRule;
pub use dart::DartPrintRule;
pub use go::GoStyleRule;
pub use html::{HtmlInlineStyleRule, HtmlMissingAltRule};
pub use java::{JavaStyleRule, SemicolonRule};
pub use js_ts::{ConsoleLogRule, VarUsageRule};
pub use kotlin::KotlinStyleRule;
pub use lua::LuaPrintRule;
pub use php::PhpEchoRule;
pub use python::{PythonPrintRule, PythonStyleRule};
pub use r::RPrintRule;
pub use ruby::{RubyPutsRule, RubyStyleRule};
pub use rust::{RustExpectRule, RustUnwrapRule};
pub use scala::ScalaPrintRule;
pub use shell::ShellEchoRule;
pub use sql::SqlSelectStarRule;
pub use swift::SwiftPrintRule;
pub use zig::ZigDebugPrintRule;